#!/bin/sh

KEYDIR=/etc/dropbear

# Check for the Dropbear RSA key
if [[ ! -f $KEYDIR/dropbear_rsa_host_key || ! -f $KEYDIR/dropbear_rsa_host_key.pub ]] ; then
  rm $KEYDIR/dropbear_rsa_host_key*
  echo "[`ktstamp -k`] Generating RSA key ..."
  dropbearkey -t rsa -f $KEYDIR/dropbear_rsa_host_key  | grep "^ssh-rsa " > $KEYDIR/dropbear_rsa_host_key.pub
fi

# Check for the Dropbear DSS key
if [[ ! -f $KEYDIR/dropbear_dss_host_key ]] ; then
  echo "[`ktstamp -k`] Generating DSA key ..."
  dropbearkey -t dss -f $KEYDIR/dropbear_dss_host_key > /dev/null
fi
